import json, yaml
from ..source import Source
from ..transforms import sampling_extra, input_limit

def _settings_entry(m, weak: str | None) -> dict:
    e = {"name": f"openai/{m.name}", "edit_format": m.edit_format,
         "use_repo_map": True, "streaming": True,
         "extra_params": {"max_tokens": m.output, "timeout": 5400,
                          "temperature": m.sampling.get("temperature"),
                          "top_p": m.sampling.get("top_p"),
                          "extra_body": sampling_extra(m)}}
    if weak:
        e["weak_model_name"] = weak
    return e


def emit_aider_bench(source: Source) -> str:
    """Settings for the aider BENCH scaffold: shipped models AND candidates.

    `benchmark/run_aider_docker.sh` passes the mounted settings file to `--read-model-settings`;
    without an entry for the model under test, aider sends litellm's default sampling instead of
    the registry's `generation_defaults`, which violates the production-params-verbatim rule.
    Client configs deliberately exclude `role: candidate`, so the bench needs its own carrier.
    Deliberately NOT in TARGETS — see configgen/tests/test_aider_bench.py.
    """
    task = next((m for m in source.models if m.role == "task"), None)
    weak = f"openai/{task.name}" if task else None
    benchable = [m for m in source.models if m.role in ("main", "candidate")]
    hdr = ("# GENERATED by configgen from main_models.yaml — do not edit by hand.\n"
           "# BENCH-ONLY carrier: includes role=candidate models, which are never advertised to\n"
           "# a client config. Point run_aider_docker.sh at this via AIDER_SETTINGS.\n")
    return hdr + yaml.safe_dump([_settings_entry(m, weak) for m in benchable], sort_keys=False)


def emit_aider(source: Source) -> dict:
    main = [m for m in source.models if m.role == "main"]
    task = next((m for m in source.models if m.role == "task"), None)
    weak = f"openai/{task.name}" if task else None
    settings = [_settings_entry(m, weak) for m in main]
    if task:
        settings.append({"name": f"openai/{task.name}", "edit_format": "whole",
                         "use_repo_map": False, "streaming": True,
                         "extra_params": {"api_base": f"http://localhost:{task.port}/v1",
                                          "api_key": "not-needed"}})
    metadata = {f"openai/{m.name}": {"max_input_tokens": input_limit(m),
                                     "max_output_tokens": m.output,
                                     "supports_vision": "vision" in m.capabilities,
                                     "supports_pdf_input": "vision" in m.capabilities,
                                     "litellm_provider": "openai",
                                     "mode": "chat"} for m in main}
    default = source.agent_defaults.get("aider")
    conf = {"openai-api-base": "http://localhost:8000/v1", "openai-api-key": "not-needed"}
    if default:
        conf["model"] = f"openai/{default}"
    hdr = "# GENERATED by configgen from main_models.yaml — do not edit by hand.\n"
    return {"settings": hdr + yaml.safe_dump(settings, sort_keys=False),
            "metadata": json.dumps(metadata, indent=2) + "\n",
            "conf": hdr + yaml.safe_dump(conf, sort_keys=False)}
