import json
from ..source import Source
from ..transforms import sampling_openai, sampling_extra, input_limit

_HEADER = "GENERATED by configgen from main_models.yaml — do not edit by hand."

def emit_opencode(source: Source) -> str:
    main = [m for m in source.models if m.role == "main"]
    task = next((m for m in source.models if m.role == "task"), None)
    local_models = {}
    for m in main:
        local_models[m.name] = {
            "name": m.display_name, "tool_call": True, "reasoning": True, "attachment": True,
            "limit": {"context": input_limit(m), "output": m.output},
            "options": {**sampling_openai(m), **sampling_extra(m)},
        }
    doc = {"$schema": "https://opencode.ai/config.json", "_generated": _HEADER,
           "provider": {"mlx-local": {
               "npm": "@ai-sdk/openai-compatible", "name": "mlx-serve (local)",
               "options": {"baseURL": "http://localhost:8000/v1", "apiKey": "not-needed"},
               "models": local_models}}}
    if task:
        doc["provider"]["mlx-task"] = {
            "npm": "@ai-sdk/openai-compatible", "name": "mlx task model (local)",
            "options": {"baseURL": f"http://localhost:{task.port}/v1", "apiKey": "not-needed"},
            "models": {task.name: {"name": task.display_name, "tool_call": False,
                                    "attachment": False,
                                    "limit": {"context": input_limit(task), "output": task.output}}}}
        doc["small_model"] = f"mlx-task/{task.name}"
    default = source.agent_defaults.get("opencode")
    if default:
        doc["model"] = f"mlx-local/{default}"
    doc.setdefault("plugin", ["superpowers@git+https://github.com/obra/superpowers.git"])
    return json.dumps(doc, indent=2) + "\n"
