import json
from ..source import Source
from ..transforms import input_limit

def emit_vscode(source: Source) -> str:
    models = [{"id": m.name, "name": m.display_name,
               "url": "http://localhost:8000/v1/chat/completions",
               "toolCalling": True, "vision": "vision" in m.capabilities, "thinking": True,
               "maxInputTokens": input_limit(m), "maxOutputTokens": m.output}
              for m in source.models if m.role == "main"]
    doc = [{"_generated": "GENERATED by configgen — do not edit by hand.",
            "name": "mlx-local", "vendor": "customendpoint", "apiKey": "not-needed",
            "apiType": "chat-completions", "models": models}]
    return json.dumps(doc, indent=2) + "\n"
