import json
from ..source import Source

_HDR = "// GENERATED by configgen from main_models.yaml — do not edit by hand.\n// Merge into ~/.config/zed/settings.json\n"

def emit_zed(source: Source) -> str:
    models = [{"name": m.name, "display_name": m.display_name,
               "max_tokens": m.context, "max_output_tokens": m.output,
               "interleaved_reasoning": True,
               "capabilities": {"tools": True, "images": "vision" in m.capabilities,
                                "parallel_tool_calls": True, "prompt_cache_key": False}}
              for m in source.models if m.role == "main"]
    doc = {"language_models": {"openai_compatible": {"mlx-local": {
        "api_url": "http://localhost:8000/v1", "available_models": models}}}}
    return _HDR + json.dumps(doc, indent=2) + "\n"
