#!/bin/bash
# Bring a fresh checkout on a new box to the state where every repo tool runs (P259-P262, 2026-10-10).
# Idempotent: every step verifies its pin and is skipped when already satisfied. Nothing is written
# outside the repo checkout, the generated config file and $STACK_WORKDIR.
#
#   scripts/bootstrap_machine.sh --box <label> [--workdir DIR] [--config-dir DIR] [--with-evidence]
#                                [--with-agentbench] [--skip-venv]
#
#   --box          MLX_BOX provenance label for this machine (e.g. m5max-128). Required unless the
#                  config file already declares one. Rows from different boxes never pair.
#   --workdir      STACK_WORKDIR. Default: a sibling of the checkout named <checkout>_workdir.
#   --config-dir   Where config.sh lives. Default: ${XDG_CONFIG_HOME:-$HOME/.config}/mlx_local_stack.
#   --with-evidence  Also restore the raw-evidence branch into $STACK_WORKDIR (optional, large).
#   --with-agentbench  Also build the AgentBench OS images (docker, slow).
#   --skip-venv    Do not create/sync .venv-bench (CI or a box without uv's python downloads).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
POLYGLOT_SHA=7e0611e
POLYGLOT_URL=https://github.com/Aider-AI/polyglot-benchmark
NLTK_PKGS="punkt punkt_tab averaged_perceptron_tagger averaged_perceptron_tagger_eng"
BOX=""; WORKDIR=""; CONFIG_DIR=""; WITH_EVIDENCE=0; WITH_AGENTBENCH=0; SKIP_VENV=0

while [ $# -gt 0 ]; do
  case "$1" in
    --box) BOX="$2"; shift 2 ;;
    --workdir) WORKDIR="$2"; shift 2 ;;
    --config-dir) CONFIG_DIR="$2"; shift 2 ;;
    --with-evidence) WITH_EVIDENCE=1; shift ;;
    --with-agentbench) WITH_AGENTBENCH=1; shift ;;
    --skip-venv) SKIP_VENV=1; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

say() { printf '[bootstrap] %s\n' "$*"; }
die() { printf '[bootstrap] REFUSED: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing tool: $1"; }
need git; need curl; need python3; need shasum
[ "$SKIP_VENV" = 1 ] || need uv

# --- 1. machine-local config (generated, never hand-edited on a fresh box) -------------------------
CONFIG_DIR="${CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/mlx_local_stack}"
CONFIG="$CONFIG_DIR/config.sh"
if [ -f "$CONFIG" ]; then
  say "config exists: $CONFIG (left untouched)"
  existing_box=$(sed -n 's/^export MLX_BOX="\{0,1\}\([^"]*\)"\{0,1\}.*/\1/p' "$CONFIG" | head -1)
  [ -n "$BOX" ] && [ -n "$existing_box" ] && [ "$BOX" != "$existing_box" ] \
    && die "config declares MLX_BOX=$existing_box but --box $BOX was given; edit the config instead"
  [ -n "$existing_box" ] || [ -n "$BOX" ] || die "config has no MLX_BOX; pass --box <label>"
  [ -n "$existing_box" ] || printf '\nexport MLX_BOX="%s"\n' "$BOX" >> "$CONFIG"
  existing_wd=$(sed -n 's/^export STACK_WORKDIR="\{0,1\}\([^"]*\)"\{0,1\}.*/\1/p' "$CONFIG" | head -1)
  [ -n "$WORKDIR" ] || WORKDIR=$(eval echo "${existing_wd:-$(dirname "$REPO")/$(basename "$REPO")_workdir}")
else
  [ -n "$BOX" ] || die "no config at $CONFIG; pass --box <label> (MLX_BOX provenance label for this machine)"
  WORKDIR="${WORKDIR:-$(dirname "$REPO")/$(basename "$REPO")_workdir}"
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG" <<EOF
# mlx_local_stack machine-local config, generated by scripts/bootstrap_machine.sh $(date -u +%Y-%m-%d).
# Not in the repo. Edit freely; re-running the bootstrap leaves an existing file untouched.
export STACK_REPO="$REPO"
export STACK_WORKDIR="$WORKDIR"
export POLYGLOT_DIR="\$STACK_WORKDIR/polyglot-benchmark"
export NLTK_DATA="\$STACK_WORKDIR/nltk_data"
export MLX_BOX="$BOX"          # provenance label; rows from different boxes never pair
export DISTILL_MODEL_PATH=""   # local snapshot dirs not resolvable from the hub; empty = hub only
export REMOTE_HOST=""; export REMOTE_USER=""; export REMOTE_REPO=""; export REMOTE_HOME=""
EOF
  say "wrote $CONFIG (STACK_WORKDIR=$WORKDIR, MLX_BOX=$BOX)"
fi
export STACK_WORKDIR="$WORKDIR"
mkdir -p "$STACK_WORKDIR"
case "$STACK_WORKDIR" in "$REPO"|"$REPO"/*) die "STACK_WORKDIR must be outside the checkout" ;; esac

# --- 2. submodules (forks pinned by the stack) ----------------------------------------------------
git -C "$REPO" submodule update --init --force
say "submodules: $(git -C "$REPO" submodule status | awk '{print $2"@"substr($1,1,8)}' | tr '\n' ' ')"

# --- 3. polyglot corpus at the recorded sha ------------------------------------------------------
PG="$STACK_WORKDIR/polyglot-benchmark"
if [ -d "$PG/.git" ]; then
  git -C "$PG" cat-file -e "$POLYGLOT_SHA^{commit}" 2>/dev/null || git -C "$PG" fetch -q origin
else
  git clone -q "$POLYGLOT_URL" "$PG"
fi
git -C "$PG" checkout -q "$POLYGLOT_SHA"
[ "$(git -C "$PG" rev-parse --short=7 HEAD)" = "$POLYGLOT_SHA" ] || die "polyglot-benchmark is not at $POLYGLOT_SHA"
say "polyglot-benchmark @ $POLYGLOT_SHA"

# --- 4. nltk data (IFEval vendored verifiers) ----------------------------------------------------
export NLTK_DATA="$STACK_WORKDIR/nltk_data"
PY="$REPO/.venv-bench/bin/python"; [ -x "$PY" ] || PY=python3
missing=""
for p in $NLTK_PKGS; do
  "$PY" - "$p" <<'EOF' >/dev/null 2>&1 || missing="$missing $p"
import os, sys, nltk
name = sys.argv[1]
sub = "taggers" if "tagger" in name else "tokenizers"
nltk.data.find(f"{sub}/{name}", paths=[os.environ["NLTK_DATA"]])   # only THIS workdir counts
EOF
done
if [ -n "$missing" ]; then
  if "$PY" -c "import nltk" 2>/dev/null; then
    # shellcheck disable=SC2086
    "$PY" -m nltk.downloader -d "$NLTK_DATA" $missing >/dev/null
    say "nltk data downloaded:$missing"
  else
    say "nltk not importable from $PY yet; nltk data deferred to the venv step"
    NLTK_DEFERRED=1
  fi
else
  say "nltk data present"
fi

# --- 5. benchmark-pinned opencode 2.0.20 --------------------------------------------------------
"$REPO/scripts/install_bench_opencode.sh"

# --- 6. bench venv from the exact pins ----------------------------------------------------------
if [ "$SKIP_VENV" = 0 ]; then
  VENV="$REPO/.venv-bench"
  [ -x "$VENV/bin/python" ] || uv venv --python 3.12 "$VENV" >/dev/null
  (cd "$REPO" && uv pip sync --python "$VENV/bin/python" benchmark/requirements-bench.lock >/dev/null)
  "$VENV/bin/python" -c "import mlx.core, mlx_vlm, mlx_serve, pytest" || die ".venv-bench does not import mlx/mlx_vlm/mlx_serve/pytest"
  say ".venv-bench synced from benchmark/requirements-bench.lock (mlx $("$VENV/bin/python" -c 'import mlx.core as m; print(m.__version__)'))"
  if [ "${NLTK_DEFERRED:-0}" = 1 ]; then
    # shellcheck disable=SC2086
    "$VENV/bin/python" -m nltk.downloader -d "$NLTK_DATA" $missing >/dev/null
    say "nltk data downloaded:$missing"
  fi
elif [ "${NLTK_DEFERRED:-0}" = 1 ]; then
  die "nltk data missing ($missing) and --skip-venv given; install nltk and re-run"
fi

# --- 7. optional: raw evidence, AgentBench images --------------------------------------------------
if [ "$WITH_EVIDENCE" = 1 ]; then
  git -C "$REPO" fetch -q origin evidence
  git -C "$REPO" archive origin/evidence | tar -x -C "$STACK_WORKDIR"
  say "evidence branch restored into $STACK_WORKDIR"
fi
[ "$WITH_AGENTBENCH" = 0 ] || "$REPO/scripts/build_agentbench_images.sh"

# --- 8. summary -----------------------------------------------------------------------------------
say "done. config=$CONFIG"
say "  STACK_WORKDIR=$STACK_WORKDIR  MLX_BOX=$(sed -n 's/^export MLX_BOX="\{0,1\}\([^"]*\)"\{0,1\}.*/\1/p' "$CONFIG" | head -1)"
say "  tests: cd benchmark && env -u STACK_WORKDIR ../.venv-bench/bin/python -m pytest -q -p no:cacheprovider bench/tests/"
say "  serving venv is separate: uv sync (uv.lock); model weights download from the hub on first load"
